adapter:  sqlite3
default: &default
  adapter:  sqlite3
  encoding: unicode
  database: tmp/redis_voteable.sqlite3
sqlite3:
  adapter: sqlite3
  database: tmp/redis_voteable.sqlite3

development:
  <<: *default
